 name: Compile LateX
  uses: vinay0410/tectonic-action@v1.1.2
  with:
    tex_path: main.tex
    # String stating whether to push output PDF, PDF will only be pushed in case of "yes"
    push: # optional, default is no
